name: Build and Publish
on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          mkdir Build
          
      - name: Setup Export Templates
        run: |
          mkdir -p $HOME/.local/share/godot/templates/3.4.2.stable
          curl https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_export_templates.tpz -o tmp/export_templates.tpz
          unzip /tmp/export_templates.tpz -d $HOME/.local/share/godot/templates/3.4.2.stable
          
      - name: Setup Godot Headless
        run: |
          curl https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_linux_headless.64.zip -o /tmp/godot_headless.zip
          unzip /tmp/godot_headless.zip
          
          /tmp/Godot_v3.4.2-stable_linux_headless.64 
          godot --export "HTML5"
          
      - name: Deploy Page
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          folder: Build/HTML5/
