name: Build and Publish
on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          mkdir Build
          
      - name: Export game
        uses: firebelley/godot-export@v3.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_export_templates.tpz
          relative_project_path: ./
          
      - name: Deploy Page
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          folder: Build/HTML5/
