name: Build and Publish
on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: Export
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          projectDir: ./
          name: wordle
          preset: HTML5
        
      - name: Deploy Page
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          folder: build
